### ISSUE TITLE
where to place code to extend create your own methods or extend the field providers

### ISSUE THREAD

**Issue by esseremmerik** [understand/understand-laravel#3]
Hello,

It seems like the extend instructions are not working for (at least) Laravel 5.1. We added the code in the providers AppServiceProvider boot method, but it seems it is not recognised by Laravel. When we try to force an exception error where we defined the extended field, the server shows a 500 error.

Any idea if these instructions are up to date as it seems the instructions are the same for the Laravel 4 repository?

Peter

**Comment by esseremmerik** [comment]
Regarding this section in the readme:


UnderstandFieldProvider::extend('getMyCustomValue', function()
{
    return 'my custom value';
});

UnderstandFieldProvider::extend('getCurrentTemperature', function()
{
    return \My\Temperature\Provider::getRoomTemperature();
});
Example

Lets assume that you have defined a custom field provider called getCurrentTemperature (as above). You should then add this to your config file as follows:

    'laravel_log' => [
        'meta' => [
            ...
            'temperature' => 'UnderstandFieldProvider::getCurrentTemperature',
            ...
        ]
    ],

**Comment by aivis** [comment]
Hi @esseremmerik

I installed Laravel v5.1.11 version and followed all steps from https://github.com/understand/understand-laravel5/blob/master/README.md - everything worked fine.

> Pay attention that `AppServiceProvider` class is located in `App\Providers` namespace and when you call `\UnderstandFieldProvider` make sure that it starts with `\` (see my example).

Here is how my `app/Providers/AppServiceProvider.php ` looks:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        \UnderstandFieldProvider::extend('getCustomValue', function()
        {
            return 'custom value';
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

and `config/understand-laravel.php`:
```php
        'laravel_log' => [
            'enabled' => true,
            'meta' => [
                'session_id' => 'UnderstandFieldProvider::getSessionId',
                'request_id' => 'UnderstandFieldProvider::getProcessIdentifier',
                'user_id' => 'UnderstandFieldProvider::getUserId',
                'env' => 'UnderstandFieldProvider::getEnvironment',
                'client_ip' => 'UnderstandFieldProvider::getClientIp',
                'custom_value' => 'UnderstandFieldProvider::getCustomValue',
```

Please let me know if this helps.

**Comment by esseremmerik** [comment]
@aivis, thanks for your reply. Your suggestion did not work at my homestead 0.3.0 server. Perhaps it is something in combination with other packages, or because I run a newer version Laravel Framework version 5.1.23 (LTS). I will try on a clean install of laravel,

**Comment by aivis** [comment]
@esseremmerik Can you please take a look at log files? `storage/logs/laravel-2015-11-...` (what exactly cause 500 error). Thanks.

**Comment by LukasLt** [comment]
Information about AppServiceProvider is gone from manual (https://www.understand.io/docs/laravel-5-event-logging) 
`Pay attention that AppServiceProvider class is located in App\Providers namespace and when you call \UnderstandFieldProvider make sure that it starts with \ (see my example).`

It took us a while to create our own custom service provider, and it worked, but it would be nice to have this info in the manual :)

**Comment by aivis** [comment]
@LukasLt Feel free to create a PR to suggest improvements. Thanks.
